web:
  image: nginx:alpine
  volumes:
    - './config/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    - "/opt/frappe/sites:/home/frappe/frappe-bench/sites"
  ports:
    - '8888:80'

app:
  image: donysukardi/erpnext:stable
  volumes:
    - "/home/frappe/frappe-bench/sites"

scheduler:
  image: donysukardi/erpnext:stable
  command: scheduler

worker-default:
  image: donysukardi/erpnext:stable
  command: worker-default

worker-long:
  image: donysukardi/erpnext:stable
  command: worker-long

worker-short:
  image: donysukardi/erpnext:stable
  command: worker-short

redis-cache:
  image: redis

redis-queue:
  image: redis

redis-socketio:
  image: redis

node-socketio:
  image: donysukardi/erpnext:stable
  command: node-socketio

